//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranDuyVu_2210900138.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDV_SACH
    {
        public string Tdv_MaSach { get; set; }
        public string Tdv_TenSach { get; set; }
        public Nullable<int> Tdv_SoTrang { get; set; }
        public Nullable<int> Tdv_NamXB { get; set; }
        public string Tdv_MaTG { get; set; }
        public Nullable<bool> Tdv_TrangThai { get; set; }
    
        public virtual TDV_TACGIA TDV_TACGIA { get; set; }
    }
}
